# workflow name
name: cd

# on events
on:
  create:
    tags:
      - v*


# jobs to run
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04,windows-2019,macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12.13

      - name: Install dependencies
        run: |
          yarn policies set-version
          yarn install --frozen-lockfile --network-timeout 1000000

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.5.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
